export const skillsData = [
  { name: 'HTML', icon: '🟧', color: '#e34c26' },
  { name: 'CSS', icon: '🟦', color: '#264de4' },
  { name: 'JavaScript', icon: '🟨', color: '#f0db4f' },
  { name: 'React', icon: '⚛️', color: '#61dbfb' },
  { name: 'Node.js', icon: '🟢', color: '#3c873a' },
  { name: 'Python', icon: '🐍', color: '#4B8BBE' },
  { name: 'Java', icon: '☕', color: '#5382a1' },
  { name: 'Express', icon: '🚀', color: '#000000' },
  { name: 'MongoDB', icon: '🍃', color: '#4DB33D' },
  { name: 'REST API', icon: '🔗', color: '#7c3aed' },
  { name: 'MySQL', icon: '🐬', color: '#e34c26' },
];

export const projectsData = [
  {
    title: 'JK Clothing - WhatsApp Commerce',
    description: 'Lightweight e-commerce site for fashion products with 1-click WhatsApp ordering. Auto-generates product details in messages for instant purchases.',
    tech: 'HTML5, CSS3, JavaScript, WhatsApp API',
    features: [
      'WhatsApp order automation (product/size/color/price)',
      'LocalStorage cart persistence',
      'Mobile-first responsive design',
      'No backend required (static site)',
    ],
    demoLink: 'https://jk-fashion.netlify.app/',
    codeLink: 'https://github.com/Suraj-Salihu/e-commerce-website-jk-closet/tree/main',
    image: '/images/jk-fashion.jpg',
  },
  {
    title: 'Sovex Task Master',
    description: 'Progressive Web App for task management with offline capabilities, project organization, and priority-based sorting.',
    tech: 'HTML5, CSS3, JavaScript, PWA',
    features: [
      'Installable PWA with service worker caching',
      'Priority-based task organization (High/Medium/Low)',
      'Project categorization with color coding',
      'Offline functionality and data persistence',
      'Dark/light mode toggle',
    ],
    demoLink: 'https://suraj-salihu.github.io/Task-Manager-PWA/',
    codeLink: 'https://github.com/Suraj-Salihu/Task-Manager-PWA/tree/main',
    image: '/images/task-Master.png',
  },
  {
    title: 'BL4MELESS Artist Portfolio',
    description: 'Professional music artist website showcasing discography, streaming links, gallery, and contact information.',
    tech: 'HTML5, CSS3, JavaScript',
    features: [
      'Interactive music player with seek functionality',
      'Multi-platform streaming links (12+ services)',
      'Responsive gallery with hover effects',
      'Embedded YouTube video showcase',
      'Contact form with FormSubmit integration',
    ],
    demoLink: 'https://bl4meless.netlify.app',
    codeLink: 'https://github.com/Suraj-Salihu/singer-website/blob/main/index.html',
    image: '/images/bl4meless-screenshot.jpg',
  },
  {
    title: 'The Movement (Tafiyar Matasa)',
    description: 'Official website for a Nigerian youth empowerment movement featuring leadership profiles, state chapters, news, and event management.',
    tech: 'HTML5, CSS3, JavaScript, EmailJS',
    demoLink: '#',
    codeLink: '#',
    image: '/images/TMLogo.png',
  },
  {
    title: 'VTU Website',
    description: 'Mobile-first virtual top-up platform for purchasing airtime, data, paying bills, and managing digital transactions.',
    tech: 'HTML5, CSS3, JavaScript, FontAwesome',
    demoLink: '#',
    codeLink: '#',
    image: '/images/vtu-screenshot.jpg',
  },
  {
    title: 'API Service',
    description: 'High-performance REST API for mobile applications with caching and rate limiting.',
    tech: 'Node.js, Redis, MongoDB, Docker',
    backend: 'Implemented JWT authentication, Redis caching layer, and comprehensive API documentation',
    demoLink: '#',
    codeLink: '#',
    status: 'in-progress',
    image: '/images/carbon.png',
  },
];

export const designWorks = {
  birthday: [
    { src: '/images/designs/birthday/birthday1.jpg', caption: 'Elegant Birthday Poster' },
    { src: '/images/designs/birthday/birthday2.jpg', caption: 'Stylish Birthday Card' },
    { src: '/images/designs/birthday/birthday3.jpg', caption: 'Creative Birthday Flyer' },
    { src: '/images/designs/birthday/birthday4.jpg', caption: 'Modern Birthday Template' },
    { src: '/images/designs/birthday/birthday5.jpg', caption: 'Charming Birthday Layout' },
    { src: '/images/designs/birthday/birthday6.jpg', caption: 'Unique Celebration Design' },
  ],
  advert: [
    { src: '/images/designs/advert/advert1.jpg', caption: 'Glamorous Makeup Ad' },
    { src: '/images/designs/advert/advert2.jpg', caption: 'Eye-Catching Graphic Design' },
    { src: '/images/designs/advert/advert3.jpg', caption: 'Luxury Perfume Promotion' },
    { src: '/images/designs/advert/advert4.jpg', caption: 'Delicious Food Ad' },
    { src: '/images/designs/advert/advert5.jpg', caption: 'Bold & Creative Graphic Concept' },
    { src: '/images/designs/advert/advert6.jpg', caption: 'Creative Social Media Banner' },
  ],
  song: [
    { src: '/images/designs/song/song1.jpg', caption: 'Creative Single Cover Design' },
    { src: '/images/designs/song/song2.jpg', caption: 'Out Now Single Release' },
    { src: '/images/designs/song/song3.jpg', caption: 'Album Cover Art' },
    { src: '/images/designs/song/song4.jpg', caption: 'Minimalist Album Artwork' },
    { src: '/images/designs/song/song5.jpg', caption: 'Lyric Visual Art' },
    { src: '/images/designs/song/song6.jpg', caption: 'Artist Branding' },
  ],
  invitation: [
    { src: '/images/designs/iv/invitation1.jpg', caption: 'Get Together Invitation' },
    { src: '/images/designs/iv/invitation2.jpg', caption: 'Wedding Event Sticker' },
    { src: '/images/designs/iv/invitation3.jpg', caption: 'Wedding Fatiha Invitation' },
    { src: '/images/designs/iv/invitation4.jpg', caption: 'Events Invitation' },
    { src: '/images/designs/iv/invitation5.jpg', caption: 'Wedding Ceremony' },
    { src: '/images/designs/iv/invitation6.jpg', caption: 'Arabic version' },
  ],
  logo: [
    { src: '/images/designs/logos/logo1.jpg', caption: 'Modern 3D Logo Design' },
    { src: '/images/designs/logos/logo2.jpg', caption: 'Creative Brand Identity' },
    { src: '/images/designs/logos/logo3.jpg', caption: 'Classic School Emblem Logo' },
    { src: '/images/designs/logos/logo4.jpg', caption: 'Typography Logo Design' },
    { src: '/images/designs/logos/logo5.jpg', caption: 'Flat Logo Design' },
    { src: '/images/designs/logos/logo6.jpg', caption: 'Iconic Brand Mark' },
  ],
  other: [
    { src: '/images/designs/other/other1.jpg', caption: 'Vibrant International Youth Day Flyer' },
    { src: '/images/designs/other/other2.jpg', caption: 'Professional Membership ID Card' },
    { src: '/images/designs/other/other3.jpg', caption: 'Celebrating PhD Achievement' },
    { src: '/images/designs/other/other4.jpg', caption: 'POP Announcement Design' },
    { src: '/images/designs/other/other5.jpg', caption: 'Elegant Certificate Template' },
    { src: '/images/designs/other/other6.jpg', caption: 'Digital Artwork' },
  ],
};
